### ISSUE TITLE
Deriving Dr based on Jamiolkowski correlation

### ISSUE THREAD

**Issue by KawanaReeves** [snakesonabrain/groundhog#25]
I encountered a problem considering one of your correlation functions. Or at least I don`t know if my approach is possible.

I'd like to derive the Dr values with the Jamiolkowski function. Beforehand I run the K0 Mayne Correlation, deriving the lateral earth pressure coefficient. Now I want the Jamiolkowski correlation to use the derived K0 values from the PCPT.data as "k0" parameter values.
In the same way the correlation function automatically obtains values for the qc parameter.
I tried to use kwargs, but the function won't extract the values for each row.
Is there a way to solve my problem?

**Comment by snakesonabrain** [comment]
The easiest way for groundhog to recognise parameters in `apply_correlation` is to give the exact same name as the function argument to your parameter column in the `.data` DataFrame.

`cpt.apply_correlation('K0 Mayne (2007) - sand', outputs={'K0 CPT [-]': 'k0'})`

`k0` is the argument name in the Jamiolkowski correlation and `'K0 CPT [-]` is the outcome of the K0 Mayne correlation.

and then use the Jamiolkowski correlation without specifying the `k0` argument (since it is already in the dataframe.

`cpt.apply_correlation('Dr Jamiolkowski et al (2003)', outputs={'Dr sat [-]': 'Dr [-]'})`

Note that you could also call your column `K0 [-]`. groundhog will convert this name to `k0` during execution of `apply_correlation`. The dictionary `PCPT_KEY_MAPPING` in the `pcpt_correlations` module has been changed in DEV to have this behaviour.

**Comment by KawanaReeves** [comment]
thanks a lot. Works fine. Appreciate your quick response.

**Comment by snakesonabrain** [comment]
Thanks for the user feedback 👍
